// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod makiatto {
        pub mod http {
            /// HTTP handler interface for Makiatto WASM functions
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod handler {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// HTTP method
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Method {
                    Get,
                    Post,
                    Put,
                    Delete,
                    Patch,
                    Head,
                    Options,
                }
                impl ::core::fmt::Debug for Method {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Method::Get => f.debug_tuple("Method::Get").finish(),
                            Method::Post => f.debug_tuple("Method::Post").finish(),
                            Method::Put => f.debug_tuple("Method::Put").finish(),
                            Method::Delete => f.debug_tuple("Method::Delete").finish(),
                            Method::Patch => f.debug_tuple("Method::Patch").finish(),
                            Method::Head => f.debug_tuple("Method::Head").finish(),
                            Method::Options => f.debug_tuple("Method::Options").finish(),
                        }
                    }
                }
                impl Method {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Method {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Method::Get,
                            1 => Method::Post,
                            2 => Method::Put,
                            3 => Method::Delete,
                            4 => Method::Patch,
                            5 => Method::Head,
                            6 => Method::Options,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// HTTP request passed to the function
                #[derive(Clone)]
                pub struct Request {
                    /// HTTP method
                    pub method: Method,
                    /// Request path (e.g., "/api/users")
                    pub path: _rt::String,
                    /// Query string without the '?' (e.g., "foo=bar&baz=qux")
                    pub query: Option<_rt::String>,
                    /// HTTP headers as key-value pairs
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    /// Request body bytes
                    pub body: Option<_rt::Vec<u8>>,
                }
                impl ::core::fmt::Debug for Request {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Request")
                            .field("method", &self.method)
                            .field("path", &self.path)
                            .field("query", &self.query)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                /// HTTP response returned by the function
                #[derive(Clone)]
                pub struct Response {
                    /// HTTP status code (e.g., 200, 404, 500)
                    pub status: u16,
                    /// Response headers as key-value pairs
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    /// Response body bytes
                    pub body: Option<_rt::Vec<u8>>,
                }
                impl ::core::fmt::Debug for Response {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Response")
                            .field("status", &self.status)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handle_request_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: i32,
                    arg9: *mut u8,
                    arg10: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let base8 = arg6;
                    let len8 = arg7;
                    let mut result8 = _rt::Vec::with_capacity(len8);
                    for i in 0..len8 {
                        let base = base8
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e8 = {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len4 = l3;
                            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                            let l5 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len7 = l6;
                            let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                            (_rt::string_lift(bytes4), _rt::string_lift(bytes7))
                        };
                        result8.push(e8);
                    }
                    _rt::cabi_dealloc(
                        base8,
                        len8 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result10 = T::handle_request(Request {
                        method: Method::_lift(arg0 as u8),
                        path: _rt::string_lift(bytes0),
                        query: match arg3 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg5;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg4.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        headers: result8,
                        body: match arg8 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len9 = arg10;
                                    _rt::Vec::from_raw_parts(arg9.cast(), len9, len9)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr11 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let Response {
                        status: status12,
                        headers: headers12,
                        body: body12,
                    } = result10;
                    *ptr11.add(0).cast::<u16>() = (_rt::as_i32(status12)) as u16;
                    let vec16 = headers12;
                    let len16 = vec16.len();
                    let layout16 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec16.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result16 = if layout16.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout16).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout16);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec16.into_iter().enumerate() {
                        let base = result16
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t13_0, t13_1) = e;
                            let vec14 = (t13_0.into_bytes()).into_boxed_slice();
                            let ptr14 = vec14.as_ptr().cast::<u8>();
                            let len14 = vec14.len();
                            ::core::mem::forget(vec14);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len14;
                            *base.add(0).cast::<*mut u8>() = ptr14.cast_mut();
                            let vec15 = (t13_1.into_bytes()).into_boxed_slice();
                            let ptr15 = vec15.as_ptr().cast::<u8>();
                            let len15 = vec15.len();
                            ::core::mem::forget(vec15);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len15;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr15.cast_mut();
                        }
                    }
                    *ptr11
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len16;
                    *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result16;
                    match body12 {
                        Some(e) => {
                            *ptr11
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec17 = (e).into_boxed_slice();
                            let ptr17 = vec17.as_ptr().cast::<u8>();
                            let len17 = vec17.len();
                            ::core::mem::forget(vec17);
                            *ptr11
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len17;
                            *ptr11
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr17.cast_mut();
                        }
                        None => {
                            *ptr11
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr11
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handle_request<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l1 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l0;
                    let len6 = l1;
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l7 = i32::from(
                        *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l7 {
                        0 => {}
                        _ => {
                            let l8 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base10 = l8;
                            let len10 = l9;
                            _rt::cabi_dealloc(base10, len10 * 1, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Main handler function - processes an HTTP request and returns a response
                    /// This is the function that WASM components must export
                    fn handle_request(req: Request) -> Response;
                }
                #[doc(hidden)]
                macro_rules! __export_makiatto_http_handler_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "makiatto:http/handler@0.1.0#handle-request")] unsafe extern "C"
                        fn export_handle_request(arg0 : i32, arg1 : * mut u8, arg2 :
                        usize, arg3 : i32, arg4 : * mut u8, arg5 : usize, arg6 : * mut
                        u8, arg7 : usize, arg8 : i32, arg9 : * mut u8, arg10 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_handle_request_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9, arg10) } } #[unsafe
                        (export_name =
                        "cabi_post_makiatto:http/handler@0.1.0#handle-request")] unsafe
                        extern "C" fn _post_return_handle_request(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_handle_request::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_makiatto_http_handler_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 6
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_http_handler_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::makiatto::http::handler::__export_makiatto_http_handler_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::makiatto::http::handler);
    };
}
#[doc(inline)]
pub(crate) use __export_http_handler_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:makiatto:http@0.1.0:http-handler:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 401] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8e\x02\x01A\x02\x01\
A\x02\x01B\x0d\x01m\x07\x03get\x04post\x03put\x06delete\x05patch\x04head\x07opti\
ons\x04\0\x06method\x03\0\0\x01ks\x01o\x02ss\x01p\x03\x01p}\x01k\x05\x01r\x05\x06\
method\x01\x04paths\x05query\x02\x07headers\x04\x04body\x06\x04\0\x07request\x03\
\0\x07\x01r\x03\x06status{\x07headers\x04\x04body\x06\x04\0\x08response\x03\0\x09\
\x01@\x01\x03req\x08\0\x0a\x04\0\x0ehandle-request\x01\x0b\x04\0\x1bmakiatto:htt\
p/handler@0.1.0\x05\0\x04\0\x20makiatto:http/http-handler@0.1.0\x04\0\x0b\x12\x01\
\0\x0chttp-handler\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compon\
ent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
