// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod makiatto {
        pub mod http {
            /// HTTP handler interface for Makiatto WASM functions
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod handler {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Node context information
                #[derive(Clone)]
                pub struct NodeContext {
                    /// Node name/identifier
                    pub name: _rt::String,
                    /// Node latitude
                    pub latitude: f64,
                    /// Node longitude
                    pub longitude: f64,
                }
                impl ::core::fmt::Debug for NodeContext {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("NodeContext")
                            .field("name", &self.name)
                            .field("latitude", &self.latitude)
                            .field("longitude", &self.longitude)
                            .finish()
                    }
                }
                /// HTTP method
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Method {
                    Get,
                    Post,
                    Put,
                    Delete,
                    Patch,
                    Head,
                    Options,
                }
                impl ::core::fmt::Debug for Method {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Method::Get => f.debug_tuple("Method::Get").finish(),
                            Method::Post => f.debug_tuple("Method::Post").finish(),
                            Method::Put => f.debug_tuple("Method::Put").finish(),
                            Method::Delete => f.debug_tuple("Method::Delete").finish(),
                            Method::Patch => f.debug_tuple("Method::Patch").finish(),
                            Method::Head => f.debug_tuple("Method::Head").finish(),
                            Method::Options => f.debug_tuple("Method::Options").finish(),
                        }
                    }
                }
                impl Method {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Method {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Method::Get,
                            1 => Method::Post,
                            2 => Method::Put,
                            3 => Method::Delete,
                            4 => Method::Patch,
                            5 => Method::Head,
                            6 => Method::Options,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// HTTP request passed to the function
                #[derive(Clone)]
                pub struct Request {
                    /// HTTP method
                    pub method: Method,
                    /// Request path (e.g., "/api/users")
                    pub path: _rt::String,
                    /// Query string without the '?' (e.g., "foo=bar&baz=qux")
                    pub query: Option<_rt::String>,
                    /// HTTP headers as key-value pairs
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    /// Request body bytes
                    pub body: Option<_rt::Vec<u8>>,
                }
                impl ::core::fmt::Debug for Request {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Request")
                            .field("method", &self.method)
                            .field("path", &self.path)
                            .field("query", &self.query)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                /// HTTP response returned by the function
                #[derive(Clone)]
                pub struct Response {
                    /// HTTP status code (e.g., 200, 404, 500)
                    pub status: u16,
                    /// Response headers as key-value pairs
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    /// Response body bytes
                    pub body: Option<_rt::Vec<u8>>,
                }
                impl ::core::fmt::Debug for Response {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Response")
                            .field("status", &self.status)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handle_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: f64,
                    arg3: f64,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: i32,
                    arg8: *mut u8,
                    arg9: usize,
                    arg10: *mut u8,
                    arg11: usize,
                    arg12: i32,
                    arg13: *mut u8,
                    arg14: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg6;
                    let bytes1 = _rt::Vec::from_raw_parts(arg5.cast(), len1, len1);
                    let base9 = arg10;
                    let len9 = arg11;
                    let mut result9 = _rt::Vec::with_capacity(len9);
                    for i in 0..len9 {
                        let base = base9
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e9 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            (_rt::string_lift(bytes5), _rt::string_lift(bytes8))
                        };
                        result9.push(e9);
                    }
                    _rt::cabi_dealloc(
                        base9,
                        len9 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result11 = T::handle_request(
                        NodeContext {
                            name: _rt::string_lift(bytes0),
                            latitude: arg2,
                            longitude: arg3,
                        },
                        Request {
                            method: Method::_lift(arg4 as u8),
                            path: _rt::string_lift(bytes1),
                            query: match arg7 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len2 = arg9;
                                        let bytes2 = _rt::Vec::from_raw_parts(
                                            arg8.cast(),
                                            len2,
                                            len2,
                                        );
                                        _rt::string_lift(bytes2)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            headers: result9,
                            body: match arg12 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len10 = arg14;
                                        _rt::Vec::from_raw_parts(arg13.cast(), len10, len10)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                    );
                    let ptr12 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let Response {
                        status: status13,
                        headers: headers13,
                        body: body13,
                    } = result11;
                    *ptr12.add(0).cast::<u16>() = (_rt::as_i32(status13)) as u16;
                    let vec17 = headers13;
                    let len17 = vec17.len();
                    let layout17 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec17.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result17 = if layout17.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout17).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout17);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec17.into_iter().enumerate() {
                        let base = result17
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t14_0, t14_1) = e;
                            let vec15 = (t14_0.into_bytes()).into_boxed_slice();
                            let ptr15 = vec15.as_ptr().cast::<u8>();
                            let len15 = vec15.len();
                            ::core::mem::forget(vec15);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len15;
                            *base.add(0).cast::<*mut u8>() = ptr15.cast_mut();
                            let vec16 = (t14_1.into_bytes()).into_boxed_slice();
                            let ptr16 = vec16.as_ptr().cast::<u8>();
                            let len16 = vec16.len();
                            ::core::mem::forget(vec16);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len16;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr16.cast_mut();
                        }
                    }
                    *ptr12
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len17;
                    *ptr12.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result17;
                    match body13 {
                        Some(e) => {
                            *ptr12
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec18 = (e).into_boxed_slice();
                            let ptr18 = vec18.as_ptr().cast::<u8>();
                            let len18 = vec18.len();
                            ::core::mem::forget(vec18);
                            *ptr12
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len18;
                            *ptr12
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr18.cast_mut();
                        }
                        None => {
                            *ptr12
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr12
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handle_request<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l1 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l0;
                    let len6 = l1;
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l7 = i32::from(
                        *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l7 {
                        0 => {}
                        _ => {
                            let l8 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base10 = l8;
                            let len10 = l9;
                            _rt::cabi_dealloc(base10, len10 * 1, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Main handler function - processes an HTTP request and returns a response
                    /// This is the function that WASM components must export
                    fn handle_request(ctx: NodeContext, req: Request) -> Response;
                }
                #[doc(hidden)]
                macro_rules! __export_makiatto_http_handler_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "makiatto:http/handler@0.1.0#handle-request")] unsafe extern "C"
                        fn export_handle_request(arg0 : * mut u8, arg1 : usize, arg2 :
                        f64, arg3 : f64, arg4 : i32, arg5 : * mut u8, arg6 : usize, arg7
                        : i32, arg8 : * mut u8, arg9 : usize, arg10 : * mut u8, arg11 :
                        usize, arg12 : i32, arg13 : * mut u8, arg14 : usize,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_handle_request_cabi::<$ty
                        > (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9,
                        arg10, arg11, arg12, arg13, arg14) } } #[unsafe (export_name =
                        "cabi_post_makiatto:http/handler@0.1.0#handle-request")] unsafe
                        extern "C" fn _post_return_handle_request(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_handle_request::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_makiatto_http_handler_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 6
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_http_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::makiatto::http::handler::__export_makiatto_http_handler_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::makiatto::http::handler);
    };
}
#[doc(inline)]
pub(crate) use __export_http_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:makiatto:http@0.1.0:http:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 438] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbb\x02\x01A\x02\x01\
A\x02\x01B\x0f\x01r\x03\x04names\x08latitudeu\x09longitudeu\x04\0\x0cnode-contex\
t\x03\0\0\x01m\x07\x03get\x04post\x03put\x06delete\x05patch\x04head\x07options\x04\
\0\x06method\x03\0\x02\x01ks\x01o\x02ss\x01p\x05\x01p}\x01k\x07\x01r\x05\x06meth\
od\x03\x04paths\x05query\x04\x07headers\x06\x04body\x08\x04\0\x07request\x03\0\x09\
\x01r\x03\x06status{\x07headers\x06\x04body\x08\x04\0\x08response\x03\0\x0b\x01@\
\x02\x03ctx\x01\x03req\x0a\0\x0c\x04\0\x0ehandle-request\x01\x0d\x04\0\x1bmakiat\
to:http/handler@0.1.0\x05\0\x04\0\x18makiatto:http/http@0.1.0\x04\0\x0b\x0a\x01\0\
\x04http\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.2\
27.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
