// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod makiatto {
        pub mod transform {
            /// Transformer interface for processing files in Makiatto
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod transformer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Node context information
                #[derive(Clone)]
                pub struct NodeContext {
                    /// Node name/identifier
                    pub name: _rt::String,
                    /// Node latitude
                    pub latitude: f64,
                    /// Node longitude
                    pub longitude: f64,
                }
                impl ::core::fmt::Debug for NodeContext {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("NodeContext")
                            .field("name", &self.name)
                            .field("latitude", &self.latitude)
                            .field("longitude", &self.longitude)
                            .finish()
                    }
                }
                /// File metadata
                #[derive(Clone)]
                pub struct FileInfo {
                    /// File path relative to domain root
                    pub path: _rt::String,
                    /// MIME type of the file
                    pub mime_type: _rt::String,
                    /// File size in bytes
                    pub size: u64,
                }
                impl ::core::fmt::Debug for FileInfo {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("FileInfo")
                            .field("path", &self.path)
                            .field("mime-type", &self.mime_type)
                            .field("size", &self.size)
                            .finish()
                    }
                }
                /// Transform result
                #[derive(Clone)]
                pub struct TransformResult {
                    /// Transformed file content
                    pub content: _rt::Vec<u8>,
                    /// Optional new MIME type (if transformation changes the type)
                    pub mime_type: Option<_rt::String>,
                    /// Optional additional headers to set
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                }
                impl ::core::fmt::Debug for TransformResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("TransformResult")
                            .field("content", &self.content)
                            .field("mime-type", &self.mime_type)
                            .field("headers", &self.headers)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_transform_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: f64,
                    arg3: f64,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: i64,
                    arg9: *mut u8,
                    arg10: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg5;
                    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
                    let len2 = arg7;
                    let bytes2 = _rt::Vec::from_raw_parts(arg6.cast(), len2, len2);
                    let len3 = arg10;
                    let result4 = T::transform(
                        NodeContext {
                            name: _rt::string_lift(bytes0),
                            latitude: arg2,
                            longitude: arg3,
                        },
                        FileInfo {
                            path: _rt::string_lift(bytes1),
                            mime_type: _rt::string_lift(bytes2),
                            size: arg8 as u64,
                        },
                        _rt::Vec::from_raw_parts(arg9.cast(), len3, len3),
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Some(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let TransformResult {
                                content: content6,
                                mime_type: mime_type6,
                                headers: headers6,
                            } = e;
                            let vec7 = (content6).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                            match mime_type6 {
                                Some(e) => {
                                    *ptr5
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr5
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr5
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                None => {
                                    *ptr5
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec12 = headers6;
                            let len12 = vec12.len();
                            let layout12 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec12.len() * (4 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result12 = if layout12.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout12).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout12);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec12.into_iter().enumerate() {
                                let base = result12
                                    .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let (t9_0, t9_1) = e;
                                    let vec10 = (t9_0.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
                                    let vec11 = (t9_1.into_bytes()).into_boxed_slice();
                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                    let len11 = vec11.len();
                                    ::core::mem::forget(vec11);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len11;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr11.cast_mut();
                                }
                            }
                            *ptr5
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr5
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result12;
                        }
                        None => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_transform<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                            let l4 = i32::from(
                                *arg0
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l4 {
                                0 => {}
                                _ => {
                                    let l5 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                            }
                            let l7 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base13 = l7;
                            let len13 = l8;
                            for i in 0..len13 {
                                let base = base13
                                    .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l9 = *base.add(0).cast::<*mut u8>();
                                    let l10 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                    let l11 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l12 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l11, l12, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base13,
                                len13 * (4 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                    }
                }
                pub trait Guest {
                    /// Main transform function - processes a file and returns transformed content
                    /// This is the function that WASM components must export
                    ///
                    /// Returns option<transform-result>:
                    /// - some(result) if the file should be transformed
                    /// - none if the file should pass through unchanged
                    fn transform(
                        ctx: NodeContext,
                        info: FileInfo,
                        content: _rt::Vec<u8>,
                    ) -> Option<TransformResult>;
                }
                #[doc(hidden)]
                macro_rules! __export_makiatto_transform_transformer_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "makiatto:transform/transformer@0.1.0#transform")] unsafe extern
                        "C" fn export_transform(arg0 : * mut u8, arg1 : usize, arg2 :
                        f64, arg3 : f64, arg4 : * mut u8, arg5 : usize, arg6 : * mut u8,
                        arg7 : usize, arg8 : i64, arg9 : * mut u8, arg10 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_transform_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6, arg7, arg8, arg9, arg10) } } #[unsafe (export_name =
                        "cabi_post_makiatto:transform/transformer@0.1.0#transform")]
                        unsafe extern "C" fn _post_return_transform(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_transform::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_makiatto_transform_transformer_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_transform_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::makiatto::transform::transformer::__export_makiatto_transform_transformer_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::makiatto::transform::transformer);
    };
}
#[doc(inline)]
pub(crate) use __export_transform_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:makiatto:transform@0.1.0:transform:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 416] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa0\x02\x01A\x02\x01\
A\x02\x01B\x0d\x01r\x03\x04names\x08latitudeu\x09longitudeu\x04\0\x0cnode-contex\
t\x03\0\0\x01r\x03\x04paths\x09mime-types\x04sizew\x04\0\x09file-info\x03\0\x02\x01\
p}\x01ks\x01o\x02ss\x01p\x06\x01r\x03\x07content\x04\x09mime-type\x05\x07headers\
\x07\x04\0\x10transform-result\x03\0\x08\x01k\x09\x01@\x03\x03ctx\x01\x04info\x03\
\x07content\x04\0\x0a\x04\0\x09transform\x01\x0b\x04\0$makiatto:transform/transf\
ormer@0.1.0\x05\0\x04\0\"makiatto:transform/transform@0.1.0\x04\0\x0b\x0f\x01\0\x09\
transform\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.\
227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
