name: CI

permissions:
  pull-requests: write
  contents: write

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          cargo build
          cargo test --workspace --exclude integration-tests

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build makiatto-builder image
        run: docker build -f tests/dockerfiles/makiatto_builder.Dockerfile -t makiatto-builder:latest .
      - name: Build ubuntu_base image
        run: docker build -f tests/dockerfiles/ubuntu_base.Dockerfile -t makiatto-test-ubuntu_base:latest .
      - name: Build ubuntu_daemon image
        run: docker build -f tests/dockerfiles/ubuntu_daemon.Dockerfile -t makiatto-test-ubuntu_daemon:latest .
      - name: Extract makiatto binary from builder
        run: |
          mkdir -p target/tests
          docker run --rm -v $PWD/target/tests:/output makiatto-builder:latest sh -c "cp /makiatto /output/"
          sudo chown -R $USER:$USER target/
      - name: Run integration tests
        run: cargo test --package integration-tests

  clippy:
    name: Check for common code mistakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --workspace --tests -- -D warnings

  fmt:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    if: github.ref == 'refs/heads/main'
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
